export const app = {
    SET_SEARCHER: 'SET_SEARCHER',
    SET_HOT_DISEASES: 'SET_HOT_DISEASES',
    SET_DEPARTMENT_LIST: 'SET_DEPARTMENT_LIST',
    SET_KEYSTONE_LIST: 'SET_KEYSTONE_LIST',
    SET_CANCER_LIST: 'SET_CANCER_LIST'
}
